---
title: "NES-LTER Attune flow cytometer discrete sample data package assembly"
author: "Stace Beaulieu"
date: "2024-01-05"
output: html_notebook
---

Libraries used

```{r}
# two of the required packages are installed from GitHub
# library(remotes)
# remotes::install_github("EDIorg/EMLassemblyline")
# remotes::install_github("WHOIGit/ediutilities")

library(EMLassemblyline)
library(ediutilities)
library(here)
library(lubridate)
```

Read data table

```{r}
data_table <- read.csv(here('attune-transect-discrete-samples.csv'))
#data_table$date = ymd_hms(data_table$date)
summary(data_table)
```

Read the Excel metadata template and generate text templates used by
EMLassemblyline

```{r}
excel_to_template(here('nes-lter-attune-fcm-discrete-transect-info'), 'attune-transect-discrete-samples', rights='CCBY')
```
Generate the package and insert the parent project node into the resulting EML

```{r}
# use designated package ID
pkg_id <- 'knb-lter-nes.29.1'

make_eml(here(),
         dataset.title='Abundance, biovolume, and biomass of Synechococcus, eukaryote pico- and nano- phytoplankton, and heterotrophic bacteria from flow cytometry for water column bottle samples on NES-LTER Transect cruises, ongoing since 2018',
         data.table='attune-transect-discrete-samples.csv',
         data.table.description='Syn, picoeuk, and heterotrophic bacteria cell, biovolume, and biomass concentration from discrete water column samples on NES-LTER cruises',
         data.table.name = 'attune-transect-discrete-samples',
         temporal.coverage = temporal_coverage(data_table$date_sampled),
         geographic.description = "NES-LTER Transect",
         geographic.coordinates = geographic_coordinates(data_table$latitude, data_table$longitude),
         maintenance.description = "ongoing",
         user.id = "NES",
         user.domain = "LTER",
         other.entity = c("Settings_configuration_history_discrete_analysis.csv"),
         other.entity.description = c("Metadata for instrument settings configuration"),
         # other.entity = c("Settings_configuration_history_discrete_analysis.csv",
         #                  "AR38_attune_fcs.zip",
         #                  "AR39B_attune_fcs.zip",
         #                  "AR61B_attune_fcs.zip",
         #                  "AT46_attune_fcs.zip",
         #                  "EN608_attune_fcs.zip",
         #                  "EN644_attune_fcs.zip",
         #                  "EN649_attune_fcs.zip",
         #                  "EN655_attune_fcs.zip",
         #                  "EN657_attune_fcs.zip",
         #                  "EN661_attune_fcs.zip",
         #                  "EN668_attune_fcs.zip",
         #                  "TN368_attune_fcs.zip"
         # ),
         # other.entity.description = c("Metadata for instrument settings configuration",
         #                              "raw FCS datafiles from Cruise AR38",
         #                              "raw FCS datafiles from Cruise AR39B",
         #                              "raw FCS datafiles from Cruise AR61B",
         #                              "raw FCS datafiles from Cruise AT46",
         #                              "raw FCS datafiles from Cruise EN608",
         #                              "raw FCS datafiles from Cruise EN644",
         #                              "raw FCS datafiles from Cruise EN649",
         #                              "raw FCS datafiles from Cruise EN655",
         #                              "raw FCS datafiles from Cruise EN657",
         #                              "raw FCS datafiles from Cruise EN661",
         #                              "raw FCS datafiles from Cruise EN668",
         #                              "raw FCS datafiles from Cruise TN368"
         # ),
         package.id = pkg_id)

project_insert(edi_pkg = pkg_id, "parent_project_II_I_RAPID_SPIROPA.txt")
```
